#!/usr/bin/env python3
"""
Rebuild PK / UNIQUE / FK constraints in Postgres from the source dumps' own DDL.

The pipeline imports data with impdp exclude=constraint,ref_constraint (keys slow the
staging load and were unneeded for the 1:1 copy). This script restores the *source*
relationships authoritatively: feed it constraint sqlfiles produced by

  impdp ... dumpfile='<job>_%U.dmp' sqlfile='NMD_LOG:cons_X.sql' include=constraint,ref_constraint

It parses the ALTER TABLE ... ADD CONSTRAINT statements, lowercases identifiers to match
the converted schemas, and applies in dependency-safe order:

  1. PRIMARY KEY / UNIQUE
  2. FOREIGN KEY as NOT VALID (existence only — never blocks on data)
  3. VALIDATE CONSTRAINT per FK; ones that fail (e.g. rows impdp skipped on charset
     errors) STAY in place as NOT VALID and are reported.

Constraints on / referencing tables that aren't in Postgres (junk tables we skip,
*_ATTACH shells never loaded) are skipped and reported. Source-DISABLEd constraints
are applied NOT VALID and never validated. CHECK constraints are out of scope.

Usage:
  python build_constraints.py /state/cons_*.sql [--dry-run] [--out /state/constraints.sql]
"""
import os, re, sys, glob, argparse
import psycopg2

def pg_conn():
    return psycopg2.connect(host=os.environ["PG_HOST"], port=os.environ.get("PG_PORT", "5432"),
                            dbname=os.environ["PG_DB"], user=os.environ["PG_USER"],
                            password=os.environ["PG_PASSWORD"])

IDENT = r'"([^"]+)"'
COLS  = r'\(([^)]+)\)'

RE_PK = re.compile(
    rf'ALTER TABLE {IDENT}\.{IDENT}\s+ADD CONSTRAINT {IDENT}\s+(PRIMARY KEY|UNIQUE)\s*{COLS}', re.S)
RE_FK = re.compile(
    rf'ALTER TABLE {IDENT}\.{IDENT}\s+ADD CONSTRAINT {IDENT}\s+FOREIGN KEY\s*{COLS}\s*'
    rf'REFERENCES {IDENT}\.{IDENT}\s*{COLS}?\s*(ON DELETE (?:CASCADE|SET NULL))?', re.S)

def cols_lc(s):
    return [c.strip().strip('"').lower() for c in s.split(",")]

def q(name):  # lowercase + quote (identifiers may collide with keywords)
    return '"' + name.lower().replace('"', '') + '"'

def parse(files):
    keys, fks, seen = [], [], set()
    for path in files:
        text = open(path, encoding="utf-8", errors="replace").read()
        for stmt in text.split(";"):
            if "ADD CONSTRAINT" not in stmt: continue
            disabled = "DISABLE" in stmt
            m = RE_PK.search(stmt)
            if m and "FOREIGN KEY" not in stmt:
                sch, tbl, con, kind, cols = m.groups()
                k = (sch.lower(), tbl.lower(), con.lower())
                if k in seen: continue
                seen.add(k)
                keys.append(dict(sch=sch.lower(), tbl=tbl.lower(), con=con.lower(),
                                 kind=kind, cols=cols_lc(cols), disabled=disabled))
                continue
            m = RE_FK.search(stmt)
            if m:
                sch, tbl, con, cols, rsch, rtbl, rcols, ondel = m.groups()
                k = (sch.lower(), tbl.lower(), con.lower())
                if k in seen: continue
                seen.add(k)
                fks.append(dict(sch=sch.lower(), tbl=tbl.lower(), con=con.lower(),
                                cols=cols_lc(cols), rsch=rsch.lower(), rtbl=rtbl.lower(),
                                rcols=cols_lc(rcols) if rcols else None,
                                ondel=ondel or "", disabled=disabled))
    return keys, fks

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--out", default="/state/constraints_generated.sql")
    args = ap.parse_args()

    files = [f for pat in args.files for f in sorted(glob.glob(pat))]
    keys, fks = parse(files)
    print(f"parsed {len(keys)} key constraints (PK/UNIQUE) + {len(fks)} FKs from {len(files)} file(s)")

    pg = pg_conn(); pg.autocommit = True
    cur = pg.cursor()
    cur.execute("""SELECT table_schema||'.'||table_name FROM information_schema.tables
                   WHERE table_schema IN ('mfom','nmdr','vsb','xlsx','etl_stage')""")
    existing = {r[0] for r in cur.fetchall()}

    out = open(args.out, "w")
    out.write("-- generated by etl/build_constraints.py from the dumps' own constraint DDL\n")
    stats = dict(key_ok=0, key_fail=0, fk_ok=0, fk_novalid=0, fk_fail=0, skipped=0)
    skipped, failures, not_valid = [], [], []

    def run(sql, on_fail):
        out.write(sql + ";\n")
        if args.dry_run: return True
        try:
            cur.execute(sql); return True
        except Exception as e:
            on_fail(str(e).split("\n")[0]); return False

    # ---- phase 1: PK / UNIQUE ----
    for k in keys:
        t = f"{k['sch']}.{k['tbl']}"
        if t not in existing:
            skipped.append(f"{k['kind']} {k['con']} on missing {t}"); stats["skipped"] += 1; continue
        sql = (f'ALTER TABLE ONLY {q(k["sch"])}.{q(k["tbl"])} ADD CONSTRAINT {q(k["con"])} '
               f'{k["kind"]} (' + ", ".join(q(c) for c in k["cols"]) + ")")
        if run(sql, lambda e, k=k: failures.append(f"{k['kind']} {k['con']}: {e}")):
            stats["key_ok"] += 1
        else:
            stats["key_fail"] += 1

    # ---- phase 2: FKs, NOT VALID ----
    applied_fks = []
    for f in fks:
        t, rt = f"{f['sch']}.{f['tbl']}", f"{f['rsch']}.{f['rtbl']}"
        if t not in existing or rt not in existing:
            skipped.append(f"FK {f['con']} {t} -> {rt} (missing table)"); stats["skipped"] += 1; continue
        ref = f'{q(f["rsch"])}.{q(f["rtbl"])}' + \
              ((" (" + ", ".join(q(c) for c in f["rcols"]) + ")") if f["rcols"] else "")
        sql = (f'ALTER TABLE {q(f["sch"])}.{q(f["tbl"])} ADD CONSTRAINT {q(f["con"])} '
               f'FOREIGN KEY (' + ", ".join(q(c) for c in f["cols"]) + f') REFERENCES {ref} '
               f'{f["ondel"]} NOT VALID')
        if run(sql, lambda e, f=f: failures.append(f"FK {f['con']}: {e}")):
            applied_fks.append(f)
        else:
            stats["fk_fail"] += 1

    # ---- phase 3: validate (skip source-DISABLEd) ----
    for f in applied_fks:
        if f["disabled"]:
            not_valid.append(f"{f['con']} (disabled in source)"); stats["fk_novalid"] += 1; continue
        sql = f'ALTER TABLE {q(f["sch"])}.{q(f["tbl"])} VALIDATE CONSTRAINT {q(f["con"])}'
        if run(sql, lambda e, f=f: not_valid.append(f"{f['con']}: {e}")):
            stats["fk_ok"] += 1
        else:
            stats["fk_novalid"] += 1

    out.close()
    print(f"\nkeys applied: {stats['key_ok']}  failed: {stats['key_fail']}")
    print(f"FKs valid: {stats['fk_ok']}  kept NOT VALID: {stats['fk_novalid']}  failed: {stats['fk_fail']}")
    print(f"skipped (missing tables): {stats['skipped']}")
    if failures:
        print("\n-- FAILURES --")
        for s in failures[:40]: print("  " + s)
    if not_valid:
        print("\n-- FKs left NOT VALID (data violates or source-disabled) --")
        for s in not_valid[:40]: print("  " + s)
    if skipped:
        print(f"\n-- skipped: {len(skipped)} (first 15) --")
        for s in skipped[:15]: print("  " + s)

if __name__ == "__main__":
    main()
